# Generated by Django 3.0.3 on 2020-05-14 06:00

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200512_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='date',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
