# Generated by Django 3.0.3 on 2020-05-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20200514_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='date',
        ),
    ]
