# Generated by Django 3.0.3 on 2020-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todolistitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='date',
            field=models.DateField(default='2020-05-14'),
        ),
    ]
