# Generated by Django 3.0.3 on 2020-05-14 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20200514_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 10, 33, 38, 60495, tzinfo=utc)),
        ),
    ]
