# Generated by Django 3.0.3 on 2020-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20200514_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='future',
            field=models.BooleanField(default=False),
        ),
    ]
