# Generated by Django 3.0.3 on 2020-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_todolistitem_future'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='future',
        ),
    ]
